### ISSUE TITLE
This Manifest isn't working

### ISSUE THREAD

**Issue by glenrobson** [internetarchive/iiif#25] opened 2023-09-28 16:17 UTC
https://iiif.archive.org/iiif/phantasmion-x/manifest.json

https://archive.org/details/phantasmion-x

**Comment by hadro** [comment] 2023-09-28 17:29
The solution for #11 that will be addressed when #22 gets merged in will fix this

**Comment by glenrobson** [comment] 2023-09-28 17:38
Great, I just tested it with the post-meeting-fixes and it works OK. Looks like similar issues with spaces in the filename.

**Comment by hadro** [comment] 2023-10-26 19:11
Fix for this has been merged into `main`

**Comment by digitaldogsbody** [comment] 2023-11-23 00:33
I've noticed that this item appears to be broken again :(

The other items mentioned in #11 are all still working ok, so there might be a secondary problem here or a regression we introduced since the `post-meeting-fixes` branch.

**Comment by hadro** [comment] 2023-11-23 00:39
Good news, I think the code is fine, the item is gone :) https://archive.org/details/phantasmion-x

**Closed** 2023-11-23 03:10 UTC
Labels: bug

**Comment by digitaldogsbody** [comment] 2023-11-23 09:27
Good spot, thanks!
